### ISSUE TITLE
BlockMetalGitter - Crash

### ISSUE THREAD

**Issue by Wugand** [Redsnake-Games/Futurepack#5]
Absturz beim klick (LMT) auf einen unlakierten Gitterblock (BlockMetalGitter) im Gamemode 0:

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=metadata, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockState{block=fp:metallGitterBlock, properties=[]}
	at net.minecraft.block.state.BlockState$StateImplementation.getValue(BlockState.java:167)
	at futurepack.common.block.BlockMetalGitter.getPlayerRelativeBlockHardness(BlockMetalGitter.java:66)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_180511_b(PlayerControllerMP.java:250)
	at net.minecraft.client.Minecraft.clickMouse(Minecraft.java:1513)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:2119)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1081)
	at net.minecraft.client.Minecraft.run(Minecraft.java:376)
	at net.minecraft.client.main.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)

**Comment by mcenderdragon** [comment]
Done
