### ISSUE TITLE
BlockMetalSlap - Chrash

### ISSUE THREAD

**Issue by Wugand** [Redsnake-Games/Futurepack#6]
Abstürz beim platzieren einer 2. Stufe auf eine existente

java.lang.IllegalArgumentException: Cannot get property null as it does not exist in BlockState{block=fp:metalSlap0, properties=[half]}
	at net.minecraft.block.state.BlockState$StateImplementation.getValue(BlockState.java:167)
	at net.minecraft.item.ItemSlab.canPlaceBlockOnSide(ItemSlab.java:104)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_178890_a(PlayerControllerMP.java:423)
	at net.minecraft.client.Minecraft.rightClickMouse(Minecraft.java:1565)
	at net.minecraft.client.Minecraft.runTick(Minecraft.java:2124)
	at net.minecraft.client.Minecraft.runGameLoop(Minecraft.java:1081)
	at net.minecraft.client.Minecraft.run(Minecraft.java:376)
	at net.minecraft.client.main.Main.main(Main.java:117)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at net.minecraftforge.gradle.GradleStartCommon.launch(Unknown Source)
	at GradleStart.main(Unknown Source)

**Comment by mcenderdragon** [comment]
Done
